name: 'Pronamic WordPress directory plugin deploy'
description: 'Deploy release to the Pronamic plugin directory.'
author: 'pronamic'

branding:
  icon: 'upload-cloud'
  color: 'orange'

inputs:
  slug:
    description: 'WordPress plugin slug.'
    required: true
    type: string
  tag:
    description: 'Release tag name.'
    required: true
    type: string
  username:
    description: 'Pronamic plugin directory username.'
    required: true
    type: string
  password:
    description: 'Pronamic plugin directory password.'
    required: true
    type: string
  latest:
    description: 'Deploy as "Latest".'
    required: false
    default: true
    type: boolean
  github-token:
    description: 'GitHub token.'
    required: false
    default: ${{ github.token }}

outputs:
  filename:
    description: 'Filename of the plugin ZIP file.'
    value: ${{ steps.filename.outputs.filename }}
  version:
    description: 'Version of the plugin.'
    value: ${{ steps.version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - id: 'version'
      name: 'Determine the version'
      run: |
        TAG=${{ inputs.tag }}
        VERSION=${TAG#v}
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      shell: bash

    - id: 'filename'
      name: 'Determine the ZIP filename'
      run: |
        FILENAME="${{ inputs.slug }}.${{ steps.version.outputs.version }}.zip"
        echo "filename=$FILENAME" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: 'Download GitHub release plugin ZIP file'
      shell: bash
      run: |
        gh release download ${{ inputs.tag }} --repo ${{ github.repository }} --pattern ${{ steps.filename.outputs.filename }}
      env:
        GH_TOKEN: ${{ inputs.github-token }}

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'pronamic-downloads'
        workload_identity_provider: 'projects/623467151959/locations/global/workloadIdentityPools/github/providers/my-repo'

    - name: 'Setup Google Cloud CLI'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Upload to Cloud Storage'
      shell: bash
      run: gcloud storage cp ${{ steps.filename.outputs.filename }} gs://wp.pronamic.download/plugins/${{ inputs.slug }}/${{ steps.filename.outputs.filename }}

    - name: 'Set latest on Cloud Storage'
      if: ${{ inputs.latest }}
      shell: bash
      run: gcloud storage cp gs://wp.pronamic.download/plugins/${{ inputs.slug }}/${{ steps.filename.outputs.filename }} gs://wp.pronamic.download/plugins/${{ inputs.slug }}/${{ inputs.slug }}.zip

    - name: 'Set latest on Pronamic WordPress directory'
      if: ${{ inputs.latest }}
      shell: bash
      run: |
        curl --fail-with-body --user "${{ inputs.username }}:${{ inputs.password }}" --data "version=${{ steps.version.outputs.version }}" --request PATCH https://wp.pronamic.directory/wp-json/pronamic-wp-extensions/v1/plugins/${{ inputs.slug }}
